### ISSUE TITLE
[NAD] Both respect and minimize tie/flush under from/to_stream

### ISSUE THREAD

**Issue by tomaszkam** [tomaszkam/date#19]
Original comment:
> Both respect and minimize tie/flush under from/to_stream

**Comment by HowardHinnant** [comment]
I believe this can be closed.

`from_stream` is handled here http://eel.is/c++draft/time.parse#10 by calling all `from_stream` overloads "unformatted input functions".

`to_stream` no longer exists.  I'm not positive how `std::format` handles this issue.  But either it is handled, or it is a `format`-wide issue, and not something chrono-specific.

**Comment by tomaszkam** [comment]
`std::format` produces an character sequence (`std::string` or the range underlying the provided output iterator), so it does not interoperate with actual streams.

**Comment by tomaszkam** [comment]
Closing per suggestion.
