### ISSUE TITLE
[LWG3230] Format specifier %y/%Y are missing locale alternative versions

### ISSUE THREAD

**Issue by tomaszkam** [tomaszkam/date#2]
Original message:
> %y format needs to document %Ey and %Oy.
> %Y format needs to document %EY.

**Comment by tomaszkam** [comment]
@HowardHinnant
As far I understand this could be potentially handled as an extension post C++20 - adding this specifier would not be breaking.

**Comment by HowardHinnant** [comment]
Actually we need these now because `strftime` has them, and we can copy that:

> %EY is replaced by the locale’s full alternative year representation.
> %Ey is replaced by the offset from %EC (year only) in the locale’s alternative
representation.
> %Oy is replaced by the last 2 digits of the year, using the locale’s alternative numeric
symbols.

**Comment by tomaszkam** [comment]
Same as for the other issue, how we would present it as issue, not new design (extension)? I think in this case, we call constiency with `strftime`.

**Comment by tomaszkam** [comment]
Discussion:
The year format specifier ('y', 'Y') are missing the locale alternative version ('%EY', '%Ey' and '%Oy'). That makes it inconsistent with the POSIX <code>strftime</code> specification (per http://pubs.opengroup.org/onlinepubs/009695399/functions/strftime.html):
> %Ey   Replaced by the offset from %EC (year only) in the locale's alternative representation.
> %EY   Replaced by the full alternative year representation.
> %Oy   Replaced by the year (offset from %C ) using the locale's alternative numeric symbols. 

and  <code>parse</code> specifiers (http://eel.is/c++draft/time.parse) that accepts these modified command.

Drafting note:
For the '%Oy' specifier we preserve consistency with the current specification for '%Od' and '%Oe' from  
"Meaning of <code>format</code> conversion specifier" (http://eel.is/c++draft/time.format#tab:time.format.spec):
> The modified command <code>%Od</code> produces the locale's alternative representation.
> The modified command <code>%Oe</code> produces the locale's alternative representation.

, as their corresponding POSIX specification is matching one for `%Oy`:

>%Od
>    Replaced by the day of the month, using the locale's alternative numeric symbols, filled as needed with leading zeros if there is any alternative symbol for zero; otherwise, with leading spaces.
>%Oe
>   Replaced by the day of the month, using the locale's alternative numeric symbols, filled as needed with leading spaces.

Proposed wording:
Change the '%y' entry in the "Table 87 — Meaning of <code>format</code> flags" as follows:
The last two decimal digits of the year. If the result is a single digit it is prefixed by 0.
<ins>The modified command <code>%Oy</code> produces the locale's alternative representation.
The modified command <code>%Ey</code> produces the locale’s alternative representation of offset from <code>%EC</code> (year only).</ins>

Change the '%Y' entry in the "Table 87 — Meaning of <code>format</code> flags" as follows:
The year as a decimal number.
If the result is less than four digits it is left-padded with <code>0</code> to four digits.
<ins>The modified command <code>%EY</code> produces the locale's alternative full year representation.</ins>
