### ISSUE TITLE
[LWG3269] Parse manipulators do not specify the result of the extraction from stream

### ISSUE THREAD

**Issue by tomaszkam** [tomaszkam/date#20]
Original comment:
> Add to parse manipulators:
>
> The expression `is >> parse(...)` shall have type `...` and value `is`.

**Comment by tomaszkam** [comment]
@HowardHinnant:
Do you think these could be addressed by just adding 'and returns `is`' to the all Remarks clauses:
> Returns: A manipulator that, when extracted from a `basic_­istream<charT, traits>` `is`, calls `from_stream(is, fmt.c_­str(), tp, addressof(abbrev), &offset)` <ins> and returns `is`</ins>.

**Comment by HowardHinnant** [comment]
It would be safer to mimic existing wording:  http://eel.is/c++draft/std.manip#2

We need to be clear that we're returning `is` by lvalue-reference.

**Comment by tomaszkam** [comment]
Discussion:
All <code>parse</code> manipulators for the <code>chrono</code> types does not specify the result of the extraction from the stream, as consequence they cannot be chained with the other read operations (at least portably). For example the following code is not required to work:
<pre>
std::chrono::sys_stime s; int x;
std::cin >> std::chrono::parse("%X", s) >> x;
</pre>

Drafting note: 
As a drive-by fix the Remarks element is also converted to a Constraints element.
The wording integrates resolution for LWG 3186.

Proposed resolution:
Apply following changes to [time.parse] Parsing:
template<class charT, class traits, class Alloc, class Parsable>
  unspecified
    parse(const basic_string<charT, traits, Alloc>& fmt, Parsable& tp);

<ins>Let <code>is</code> be an object of type <ins>basic_­istream<charT, traits></code>.<ins>

<del>Remarks</del><ins>Constraints</ins>: <del>This function shall not participate in overload resolution unless</del><ins>The expression</ins>
 from_stream(declval<basic_istream<charT, traits>&>(), fmt.c_str(), tp)
is <del>a valid expression</del><ins>well-formed expression when treated as an unevaluated operand</ins>.

Returns: A manipulator that, <del>when extracted from a <code>basic_­istream<charT, traits> is</code>,</del><ins>the expression <code>is >> parse(fmt, tp)</code> have a type <code>basic_­istream<charT, traits>&</code>, value <code>is</code>, and</ins> calls <code>from_­stream(is, fmt.c_­str(), tp)</code>.

template<class charT, class traits, class Alloc, class Parsable>
  unspecified
    parse(const basic_string<charT, traits, Alloc>& fmt, Parsable& tp,
          basic_string<charT, traits, Alloc>& abbrev);

<ins>Let <code>is</code> be an object of type <ins>basic_­istream<charT, traits></code>.<ins>

<del>Remarks</del><ins>Constraints</ins>: <del>This function shall not participate in overload resolution unless</del><ins>The expression</ins>
from_stream(declval<basic_istream<charT, traits>&>(), fmt.c_str(), tp, addressof(abbrev))
is <del>a valid expression</del><ins>well-formed expression when treated as an unevaluated operand</ins>.

Returns: A manipulator that, <del>when extracted from a <code>basic_­istream<charT, traits> is</code>,</del><ins>the expression <code>is >> parse(fmt, tp, abbrev)</code> have a type <code>basic_istream<charT, traits>&</code>, value <code>is</code>, and</ins> calls <code>from_­stream(is, fmt.c_­str(), tp, addressof(abbrev))</code>.

template<class charT, class traits, class Alloc, class Parsable>
  unspecified
    parse(const basic_string<charT, traits, Alloc>& fmt, Parsable& tp,
          minutes& offset);

<ins>Let <code>is</code> be an object of type <ins>basic_­istream<charT, traits></code>.<ins>

<del>Remarks</del><ins>Constraints</ins>: <del>This function shall not participate in overload resolution unless</del><ins>The expression</ins>
from_stream(declval<basic_istream<charT, traits>&>(), fmt.c_str(), tp, <del>nullptr</del><ins>declval<basic_string<charT, traits, Alloc>*>()</ins>, &offset)
is <del>a valid expression</del><ins>well-formed expression when treated as an unevaluated operand</ins>.

Returns: A manipulator that, <del>when extracted from a <code>basic_­istream<charT, traits> is</code>,</del><ins>the expression <code>is >> parse(fmt, tp, offset)</code> have a type <code>basic_stream<charT, traits>&</code>, value <code>is</code>, and</ins> calls <code>from_­stream(is, fmt.c_­str(), tp, <del>nullptr</del><ins>static_cast<basic_string<charT, traits, Alloc>*>(nullptr)</ins>, &offset)</code>.

template<class charT, class traits, class Alloc, class Parsable>
  unspecified
    parse(const basic_string<charT, traits, Alloc>& fmt, Parsable& tp,
          basic_string<charT, traits, Alloc>& abbrev, minutes& offset);

<del>Remarks</del><ins>Constraints</ins>: <del>This function shall not participate in overload resolution unless</del><ins>The expression</ins>
from_stream(declval<basic_istream<charT, traits>&>(),
            fmt.c_str(), tp, addressof(abbrev), &offset)
is <del>a valid expression</del><ins>well-formed expression when treated as an unevaluated operand</ins>.

Returns: A manipulator that, <del>when extracted from a <code>basic_­istream<charT, traits> is</code>,</del><ins>the expression <code>is >> parse(fmt, tp, abbrev, offset)</code> have a type <code>basic_stream<charT, traits>&</code>, value <code>is</code>, and</ins> calls <code>from_stream(is, fmt.c_­str(), tp, addressof(abbrev), &offset)</code>.

**Comment by HowardHinnant** [comment]
Missing `&` on each "have a type `basic_stream<charT, traits>`".

**Comment by tomaszkam** [comment]
Thanks, updated the wording here and also in the submission.
