### ISSUE TITLE
[LWG3252] Parse locale's aware modifiers for commands are not consistent with POSIX spec

### ISSUE THREAD

**Issue by tomaszkam** [tomaszkam/date#37]
The [time.parse.spec] Meaning of <code>parse</code> flag does not support a modified commands of 'OI%', '%OU', '%OW', while the formating supports it. Also POSIX strptime supports it (http://pubs.opengroup.org/onlinepubs/9699919799/functions/strptime.html).

We claim to support '%Ou', '%OC' that is not supported by POSIX.

**Comment by tomaszkam** [comment]
@HowardHinnant:
Is this just an oversight or the intended design? I am lacking the knowledge about <code>time_get</code> to confirm it.

**Comment by HowardHinnant** [comment]
This looks like an oversight, both in the spec and the implementation.  If POSIX strptime supports it, so should we:

https://pubs.opengroup.org/onlinepubs/009695399/functions/strptime.html

**Comment by tomaszkam** [comment]
Added also '%OV'.

**Comment by HowardHinnant** [comment]
Note that there are some modified flags that `strftime` supports and `strptime` doesn't (don't ask me why).  `%OV` is one such flag.  I think we should be consistent with POSIX's inconsistency. :-)  Rationale, `std::get_time` is already specified in terms of `strptime`, and we can't afford to be inventive with locale-dependent things.

**Comment by tomaszkam** [comment]
POSX `strptime` does not support '%Ou' while we support it, at least in spec. Should we remove it?

**Comment by HowardHinnant** [comment]
Ouch!  Yes.  That is definitely a bug on my part.  Thanks!

I only invented in a couple places for these flags, and none of them involved locale-dependent stuff.  If we are inconsistent with POSIX/C on this, it's a bug.

**Comment by tomaszkam** [comment]
There is also '%OC' that does not exists in `strptime`, I assume also to be removed.

**Comment by HowardHinnant** [comment]
Thanks for doing this review.  I can't believe how many of these I got wrong.  My eyes must've been crossed when I went through these...

**Comment by tomaszkam** [comment]
I just reported the issue with missing modifiers in format for '%y'/'%Y' and decided it is worth to double check it against POSIX spec. Then checked it against parse table and found these inconsistencies.

**Comment by tomaszkam** [comment]
I have found also https://github.com/tomaszkam/date/issues/34, but reported it to be fixed editorially, as it is an obvious typo.

**Comment by tomaszkam** [comment]
Discussion:
The current specification of the locale modifiers for the parse flags in "[tab:time.parse.spec] Meaning of <code>parse</code> flags" is inconsistent with the POSIX <code>strptime</code> specification (https://pubs.opengroup.org/onlinepubs/009695399/functions/strptime.html):
* new flags <code>%OC</code>, <code>%Ou</code> are added
* flags  <code>%OI</code>, <code>%OU</code>, <code>%OW</code> are missing

Per Howard's comment:
> I only invented in a couple places for these flags, and none of them involved locale-dependent stuff. If we are inconsistent with POSIX/C on this, it's a bug.
> Rationale, <code>std::get_time</code> is already specified in terms of <code>strptime</code>, and we can't afford to be inventive with locale-dependent things.

Note that, due above, the inconsistency between POSIX <code>strftime</code> specification (http://pubs.opengroup.org/onlinepubs/9699919799/functions/strftime.html) that supports <code>%Ou</code> and <code>%OV</code> that are not handled by <code>strptime</code> (https://pubs.opengroup.org/onlinepubs/009695399/functions/strptime.html) should be (by design) reflected in the "[tab:time.format.spec] Meaning of conversion specifiers" and "[tab:time.parse.spec] Meaning of <code>parse</code> flags" tables.

The <code>%d</code> modifier was addressed by http://cplusplus.github.io/LWG/lwg-active.html#3218.

Proposed wording:
Change the entries in the "[tab:time.parse.spec]— Meaning of parse flags" as follows:
Entry <code>%C</code>:
The century as a decimal number. The modified command <code>%<em>N</em>C</code> specifies the maximum number of characters to read. If <code><em>N</em></code> is not specified, the default is <code>2</code>.
Leading zeroes are permitted but not required.
The modified command<del>s</del> <code>%EC</code> <del>and <code>%OC</code></del> interpret<ins>s</ins> the locale's alternative representation of the century.

Entry <code>%I</code>:
The hour (12-hour clock) as a decimal number.
The modified command <code>%<em>N</em>I</code> specifies the maximum number of characters to read.
f <code><em>N</em></code> is not specified, the default is <code>2</code>.
Leading zeroes are permitted but not required.
<ins>The modified command <code>%OI</code> interprets the locale's alternative representation.</ins>

Entry <code>%u</code>:
The ISO weekday as a decimal number (<code>1-7</code>), where Monday is <code>1</code>.
The modified command <code>%<em>N</em>u</code> specifies the maximum number of characters to read.
If <code><em>N</em></code> is not specified, the default is <code>1</code>.
Leading zeroes are permitted but not required.
<del>The modified command <code>%Ou</code> interprets the locale's alternative representation.</del>

Entry <code>%U</code>:
The week number of the year as a decimal number.
The first Sunday of the year is the first day of week <code>01</code>.
Days of the same year prior to that are in week <code>00</code>.
The modified command <code>%<em>N</em>U</code> specifies the maximum number of characters to read.
If <code><em>N</em></code> is not specified, the default is <code>2</code>.
Leading zeroes are permitted but not required.
<ins>The modified command <code>%OU</code> interprets the locale's alternative representation.</ins>

Entry '%W':
The week number of the year as a decimal number.
The first Monday of the year is the first day of week <code>01</code>.
Days of the same year prior to that are in week <code>00</code>.
The modified command <code>%<em>N</em>W</code> specifies the maximum number of characters to read.
If <code><em>N</em></code> is not specified, the default is <code>2</code>.
Leading zeroes are permitted but not required.
<ins>The modified command <code>%OW</code> interprets the locale's alternative representation.</ins>
