### ISSUE TITLE
[LWG3271] Parsing funciton saves save and restore format state

### ISSUE THREAD

**Issue by tomaszkam** [tomaszkam/date#4]
Orginal comment:
> to_stream/from_stream sets os to the default fill, flags and width on entry
and restores the original fill, flags and with on exit.

**Comment by tomaszkam** [comment]
The format part no longer applies after migration to `std::format`.

**Comment by HowardHinnant** [comment]
Proposed wording:

27.12 Parsing [time.parse]/p10:

All from_stream overloads behave as unformatted input functions, except that they have an unspecified effect on the value returned by subsequent calls to basic_istream<>::gcount(). <ins>Any changes to made to `is.fill()`, `is.width()` or `is.flags(`) are undone prior to an ordinary or exceptional return.</ins> Each overload takes a ...

**Comment by HowardHinnant** [comment]
Mailed to LWG chair.
